cars:
  count: 1000
  arrival_time_min: 1
  arrival_time_max: 2
  shared_queue_length_max: 5
stations:
  gas:
    count: 4
    serve_time_min: 2
    serve_time_max: 5
    queue_length_max: 3
  diesel:
    count: 2
    serve_time_min: 3
    serve_time_max: 6
    queue_length_max: 3
  lpg:
    count: 1
    serve_time_min: 4
    serve_time_max: 7
    queue_length_max: 3
  electric:
    count: 1
    serve_time_min: 5
    serve_time_max: 10
    queue_length_max: 3
registers:
  count: 2
  handle_time_min: 1
  handle_time_max: 3
  queue_length_max: 1